### ISSUE TITLE
RPC Calls support.

### ISSUE THREAD

**Issue by rvalle** [zooper-corp/node-red-contrib-polkadot#1]
I would like to monitor my nodes with this.

I can make a workflow to know if they are falling behind with sync, by comparing my nodes to others of reference.

Now I would also like to check the version of RPC node software versus reference nodes.

For that I believe I need to make the call: ```rpc.system.version()```

I don't think is possible to make RPC calls now, right?

**Comment by johnuopini** [comment]
This is not possible yet, it would be enough to add a drop down option to the "state" node so instead of calling api.* methods it would call the rpc ones, happy to consider a pull request

**Comment by rvalle** [comment]
I see what you mean,

but then perhaps it would make sense to call the node "query", and having multiple query types: "state, rpc, runtime..." whatever is possible with the API.

Not sure how you fill about breaking backward compatibility? We have very low volume of downloads, this should not be an issue, what do you think?

We can do a minor/major release and warn in the doc...

**Comment by johnuopini** [comment]
We can name it "Query" in the HTML without breaking anything as long as the node name stays the same and the function name doesnt change it won't break existing flows

**Comment by rvalle** [comment]
Ok, we introduce the parameter "query type" to the "query state" node, and there we place all possible options that can follow the ```api.*```

It is also possible to be set by msg.

and then we use documentation to try to make the thing more generic.

if I could I would rename to "query api", or just "query", but I dont think it is possible to change the node name without breaking existing flows.

**Comment by rvalle** [comment]
closed by #3 

@johnuopini are you triggering release?

**Comment by johnuopini** [comment]
> are you triggering release?

Yes, release is out, also updated Polkadot API version and added name to TX
